### ISSUE TITLE
artifact "six" with named file fails

### ISSUE THREAD

**Issue by robparrott** [hierynomus/jython-gradle-plugin#6]
When using the example dependency statement from the README:

```
 jython(":six:1.9.0") {
    artifact {
      name = "six"
      extension = "py"
    }
  }
```

I get a NPE, and the "six" lib is not included.

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':client:cuttyhunk-cli:compile'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --debug option to get more log output.

* Exception is:
org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':client:cuttyhunk-cli:compile'.
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.wrapException(ErrorHandlingConfigurationResolver.java:70)
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.resolve(ErrorHandlingConfigurationResolver.java:45)

...

Caused by: java.lang.NullPointerException
        at org.gradle.internal.component.model.DefaultIvyArtifactName.hashCode(DefaultIvyArtifactName.java:106)
        at org.gradle.util.CollectionUtils.collect(CollectionUtils.java:160)
        at org.gradle.util.CollectionUtils.collect(CollectionUtils.java:151)
        at org.gradle.api.internal.artifacts.ivyservice.moduleconverter.dependencies.AbstractIvyDependencyDescriptorFactory.convertArtifacts(AbstractIvyDependencyDescriptorFactory.java:51)
        at org.gradle.api.internal.artifacts.ivyservice.moduleconverter.dependencies.ExternalModuleIvyDependencyDescriptorFactory.createDependencyDescriptor(ExternalModuleIvyDependencyDescriptorFactory.java:42)
...
```

**Comment by hierynomus** [comment]
Could you copy-paste the entire build.gradle, or a small reproduction
sample?

2016-05-24 1:58 GMT+02:00 Rob Parrott notifications@github.com:

**Comment by jonflusspferd** [comment]
I just hit this, looks like type is mandatory on artifact (take a look at the source for DefaultIvyArtifactName). So if you change it to the following it works:

```
jython(":six:1.9.0") {
    artifact {
      name = "six"
      extension = "py"
      type = "whatever"
    }
  }
```

**Comment by hierynomus** [comment]
Ahh, thanks for finding that! I'll try to make it more intuitive soon :)

**Comment by hierynomus** [comment]
With v0.6.0 I've improved the notation for downloading these kind of dependencies.
